name: Validate

on:
  push:
  pull_request:

jobs:
  hacs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v7"
      
      - uses: "hacs/action@1ebf01c408f29afcb6406bd431bc98fd8cbb15aa" # main
        name: HACS validation
        with:
          category: "integration"

      - uses: "home-assistant/actions/hassfest@58bff37c8947f690ace498be413a9b78d6f30f93" # master
          
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements_dev.txt

      - name: Flake8 lint
        uses: TrueBrain/actions-flake8@36ab8db923b9a63cfd4b87840ca2f94c117bb50e # v2
        with:
          path: custom_components

      - name: Verify import sorting
        run: isort --diff --check-only custom_components